#!/bin/bash
# process all benchmarks possible!  
srcRoot="/scratch/safe/spec2006/benchspec/CPU2006"
asmRoot="/scratch/safe/asplos2014_binaries/asm"

declare -A asm2src;

asm2src["perlbench_base.gcc-mipsel-32b.asm"]="400.perlbench/"
asm2src["bzip2_base.gcc-mipsel-32b.asm"]="401.bzip2/"
asm2src["gcc_base.gcc-mipsel-32b.asm"]="403.gcc/"
asm2src["-"]="410.bwaves/"
asm2src["-"]="416.gamess/"
asm2src["mcf_base.gcc-mipsel-32b.asm"]="429.mcf/"
asm2src["milc_base.gcc-mipsel-32b.asm"]="433.milc/"
asm2src["-"]="434.zeusmp/"
asm2src["-"]="435.gromacs/"
asm2src["-"]="436.cactusADM/"
asm2src["-"]="437.leslie3d/"
asm2src["namd_base.gcc-mipsel-32b.asm"]="444.namd/"
asm2src["gobmk_base.gcc-mipsel-32b.asm"]="445.gobmk/"
asm2src["dealII_base.gcc-mipsel-32b.asm"]="447.dealII/"
asm2src["soplex_base.gcc-mipsel-32b.asm"]="450.soplex/"
asm2src["povray_base.gcc-mipsel-32b.asm"]="453.povray/"
asm2src["-"]="454.calculix/"
asm2src["hmmer_base.gcc-mipsel-32b.asm"]="456.hmmer/"
asm2src["sjeng_base.gcc-mipsel-32b.asm"]="458.sjeng/"
asm2src["-"]="459.GemsFDTD/"
asm2src["libquantum_base.gcc-mipsel-32b.asm"]="462.libquantum/"
asm2src["h264ref_base.gcc-mipsel-32b.asm"]="464.h264ref/"
asm2src["-"]="465.tonto/"
asm2src["lbm_base.gcc-mipsel-32b.asm"]="470.lbm/"
asm2src["omnetpp_base.gcc-mipsel-32b.asm"]="471.omnetpp/"
asm2src["astar_base.gcc-mipsel-32b.asm"]="473.astar/"
asm2src["-"]="481.wrf/"
asm2src["sphinx_livepretend_base.gcc-mipsel-32b.asm"]="482.sphinx3/"
asm2src["-"]="483.xalancbmk/"
asm2src["specrand_base_f.asm"]="998.specrand/"
asm2src["specrand_base_i.asm"]="999.specrand/"
unset -v asm2src["-"] # destroy our "-" placeholder

for k in "${!asm2src[@]}"; do
  echo "${asmRoot}/${k} => ${srcRoot}/${asm2src[${k}]}"
done

#asm2src["perlbench_base.gcc-mipsel-32b.asm"]=
#asm2src["bzip2_base.gcc-mipsel-32b.asm"]=
#asm2src["gcc_base.gcc-mipsel-32b.asm"]=
#asm2src["-"]=
#asm2src["-"]=
#asm2src["mcf_base.gcc-mipsel-32b.asm"]=
#asm2src["milc_base.gcc-mipsel-32b.asm"]=
#asm2src["-"]=
#asm2src["-"]=
#asm2src["-"]=
#asm2src["-"]=
#asm2src["namd_base.gcc-mipsel-32b.asm"]=
#asm2src["gobmk_base.gcc-mipsel-32b.asm"]=
#asm2src["dealII_base.gcc-mipsel-32b.asm"]=
#asm2src["soplex_base.gcc-mipsel-32b.asm"]=
#asm2src["povray_base.gcc-mipsel-32b.asm"]=
#asm2src["-"]=
#asm2src["hmmer_base.gcc-mipsel-32b.asm"]=
#asm2src["sjeng_base.gcc-mipsel-32b.asm"]=
#asm2src["-"]=
#asm2src["libquantum_base.gcc-mipsel-32b.asm"]=
#asm2src["h264ref_base.gcc-mipsel-32b.asm"]=
#asm2src["-"]=
#asm2src["lbm_base.gcc-mipsel-32b.asm"]=
#asm2src["omnetpp_base.gcc-mipsel-32b.asm"]=
#asm2src["astar_base.gcc-mipsel-32b.asm"]=
#asm2src["-"]=
#asm2src["sphinx_livepretend_base.gcc-mipsel-32b.asm"]=
#asm2src["-"]=
#asm2src["specrand_base_f.asm"]=
#asm2src["specrand_base_i.asm"]=


